name: 'Copy'
on:
  push:
    branches:
      - 'main'
jobs:
  copy:
    runs-on: 'ubuntu-latest'
    timeout-minutes: 15
    steps:
      - name: 'Check out repository'
        uses: 'actions/checkout@v4'
        with:
          fetch-depth: 0
      - name: 'Set up SSH key'
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.GITLAB_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan gitlab.com >> ~/.ssh/known_hosts
      - name: 'Copy'
        run: |
          git config --global user.name "tegebu github actions"
          git config --global user.email "actions@tegebu.com"
          git remote add gitlab git@gitlab.com:tegebu/quai.git
          git push --force gitlab main
